export const ANTIPATTERNS = [
  {
    id: 'A01-CRITICAL-color-contrast',
    category: 'accessibility',
    severity: 'CRITICAL',
    name: 'Insufficient color contrast',
    description: 'Body text contrast ratio below 4.5:1 against background',
    check: 'contrast',
  },
  {
    id: 'A02-CRITICAL-large-text-contrast',
    category: 'accessibility',
    severity: 'CRITICAL',
    name: 'Large text contrast failure',
    description: 'Large text (≥18px or ≥14px bold) contrast below 3:1',
    check: 'contrast',
  },
  {
    id: 'A03-CRITICAL-side-stripe-borders',
    category: 'visual',  
    severity: 'CRITICAL',
    name: 'Side-stripe borders',
    description: 'Border-left/right >1px as accent on cards/lists. Rewrite with full borders, tints, or nothing.',
    check: 'borders',
  },
  {
    id: 'S01-CRITICAL-skipped-headings',
    category: 'semantic',
    severity: 'CRITICAL',
    name: 'Skipped heading levels',
    description: 'HTML heading hierarchy skips levels (e.g., h1 → h3)',
    check: 'structure',
  },
  {
    id: 'S02-CRITICAL-missing-lang',
    category: 'semantic',
    severity: 'CRITICAL',
    name: 'Missing language attribute',
    description: 'HTML element lacks lang attribute',
    check: 'structure',
  },
  {
    id: 'V01-HIGH-gray-on-colored',
    category: 'visual',
    severity: 'HIGH',
    name: 'Gray text on colored background',
    description: 'Gray/muted text on colored backgrounds looks washed out. Use darker tint of background hue instead.',
    check: 'color',
  },
  {
    id: 'V02-HIGH-gradient-text',
    category: 'visual',
    severity: 'HIGH',
    name: 'Gradient text',
    description: 'background-clip: text with gradient background is decorative noise. Use solid color.',
    check: 'color',
  },
  {
    id: 'V03-HIGH-glassmorphism-default',
    category: 'visual',
    severity: 'HIGH',
    name: 'Glassmorphism as default',
    description: 'Backdrops and glass cards used decoratively. Reserve for rare purposeful moments.',
    check: 'color',
  },
  {
    id: 'V04-HIGH-hero-metric-template',
    category: 'visual',
    severity: 'HIGH',
    name: 'Hero-metric template',
    description: 'Big number + small label + gradient accent = SaaS cliché. Reject.',
    check: 'layout',
  },
  {
    id: 'V05-HIGH-identical-card-grids',
    category: 'visual',
    severity: 'HIGH',
    name: 'Identical card grids',
    description: 'Repeating icon+heading+text cards in uniform grid. Vary the pattern.',
    check: 'layout',
  },
  {
    id: 'V06-HIGH-nested-cards',
    category: 'visual',
    severity: 'HIGH',
    name: 'Nested cards',
    description: 'Cards inside cards are always wrong. Use spacing or dividers instead.',
    check: 'layout',
  },
  {
    id: 'V07-HIGH-eyebrow-every-section',
    category: 'visual',
    severity: 'HIGH',
    name: 'Eyebrow on every section',
    description: 'Small all-caps tracked label above every h2 is AI grammar. Use deliberately.',
    check: 'typography',
  },
  {
    id: 'V08-HIGH-text-overflow',
    category: 'visual',
    severity: 'HIGH',
    name: 'Text overflow',
    description: 'Heading text overflows container at narrow widths. Test at all breakpoints.',
    check: 'typography',
  },
  {
    id: 'V09-MEDIUM-purple-gradient',
    category: 'visual',
    severity: 'MEDIUM',
    name: 'Purple gradient AI tell',
    description: 'Purple-to-cyan/blue gradients are 2026 AI default. Pick brand colors instead.',
    check: 'color',
  },
  {
    id: 'V10-MEDIUM-bounce-easing',
    category: 'visual',
    severity: 'MEDIUM',
    name: 'Bounce/elastic easing',
    description: 'Bounce and elastic easings feel dated. Use ease-out-exp curves instead.',
    check: 'motion',
  },
  {
    id: 'V11-MEDIUM-tiny-radius',
    category: 'visual',
    severity: 'MEDIUM',
    name: 'Inconsistent border-radius',
    description: 'Mixed border-radius values without system. Use scale: 0, 2, 4, 8, 16, full.',
    check: 'layout',
  },
  {
    id: 'V12-MEDIUM-icon-tile-stack',
    category: 'visual',
    severity: 'MEDIUM',
    name: 'Icon tile above every heading',
    description: 'Rounded square icon tile above every section heading is AI tell.',
    check: 'layout',
  },
  {
    id: 'V13-MEDIUM-numbered-section-markers',
    category: 'visual',
    severity: 'MEDIUM',
    name: 'Numbered section markers scaffold',
    description: '01/02/03 above every section is scaffold reflex. Use for actual sequences only.',
    check: 'layout',
  },
  {
    id: 'V14-MEDIUM-line-length',
    category: 'visual',
    severity: 'MEDIUM',
    name: 'Excessive line length',
    description: 'Body text exceeds 75ch width. Cap at 65-75ch for readability.',
    check: 'typography',
  },
  {
    id: 'V15-MEDIUM-hero-scale',
    category: 'visual',
    severity: 'MEDIUM',
    name: 'Hero heading scale',
    description: 'Display heading clamp max exceeds 6rem. The page is shouting.',
    check: 'typography',
  },
  {
    id: 'V16-MEDIUM-tracking-tight',
    category: 'visual',
    severity: 'MEDIUM',
    name: 'Tight letter-spacing floor',
    description: 'Display tracking tighter than -0.04em. Letters touch. Cramped, not designed.',
    check: 'typography',
  },
  {
    id: 'V17-LOW-inter-font',
    category: 'visual',
    severity: 'LOW',
    name: 'Inter as default',
    description: 'Inter is safe but overused. Consider alternatives that express brand.',
    check: 'typography',
  },
  {
    id: 'V18-LOW-crammed-padding',
    category: 'visual',
    severity: 'LOW',
    name: 'Crammed padding',
    description: 'Content touches container edges. Add breathing room (≥16px).',
    check: 'layout',
  },
  {
    id: 'P01-HIGH-render-blocking',
    category: 'performance',
    severity: 'HIGH',
    name: 'Render-blocking resources',
    description: 'Synchronous scripts or stylesheets blocking first paint.',
    check: 'performance',
  },
  {
    id: 'P02-MEDIUM-animate-layout',
    category: 'performance',
    severity: 'MEDIUM',
    name: 'Animated layout properties',
    description: 'Animating width/height/position triggers layout. Transform/opacity instead.',
    check: 'motion',
  },
  {
    id: 'P03-MEDIUM-large-uncached-assets',
    category: 'performance',
    severity: 'MEDIUM',
    name: 'Large uncached assets',
    description: 'Images/fonts loaded without caching headers or size hints.',
    check: 'performance',
  },
  {
    id: 'I01-HIGH-tap-target-size',
    category: 'interaction',
    severity: 'HIGH',
    name: 'Small tap targets',
    description: 'Interactive elements < 44×44px. Mobile users cannot accurately tap.',
    check: 'interaction',
  },
  {
    id: 'I02-HIGH-focus-visible',
    category: 'interaction',
    severity: 'HIGH',
    name: 'Missing focus-visible',
    description: 'Interactive elements lack visible focus indicators.',
    check: 'interaction',
  },
  {
    id: 'I03-MEDIUM-dropdown-overflow',
    category: 'interaction',
    severity: 'MEDIUM',
    name: 'Dropdown clipped by overflow',
    description: 'Absolute dropdown inside overflow:hidden container is clipped.',
    check: 'interaction',
  },
  {
    id: 'I04-MEDIUM-uniform-reveal-animations',
    category: 'interaction',
    severity: 'MEDIUM',
    name: 'Uniform section reveals',
    description: 'Same entrance animation on every section. Vary by content or skip.',
    check: 'motion',
  },
  {
    id: 'I05-LOW-image-hover',
    category: 'interaction',
    severity: 'LOW',
    name: 'Image hover animation',
    description: 'Animar imágenes en hover no añade información. Animar contenedor en su lugar.',
    check: 'motion',
  },
  {
    id: 'I06-CRITICAL-no-reduced-motion',
    category: 'interaction',
    severity: 'CRITICAL',
    name: 'Missing reduced-motion alternative',
    description: 'Animations without prefers-reduced-motion alternative block motion-sensitive users.',
    check: 'motion',
  },
  {
    id: 'I07-HIGH-empty-link-text',
    category: 'semantic',
    severity: 'HIGH',
    name: 'Empty link text',
    description: 'Links with no text content (icon-only without aria-label).',
    check: 'structure',
  },
  {
    id: 'I08-HIGH-empty-button-text',
    category: 'semantic',
    severity: 'HIGH',
    name: 'Empty button text',
    description: 'Buttons with no text content and no aria-label.',
    check: 'structure',
  },
  {
    id: 'S03-HIGH-missing-alt',
    category: 'semantic',
    severity: 'HIGH',
    name: 'Missing image alt text',
    description: 'Images without alt attribute or with generic alt like "image".',
    check: 'structure',
  },
  {
    id: 'S04-HIGH-form-labels',
    category: 'semantic',
    severity: 'HIGH',
    name: 'Form inputs without labels',
    description: 'Inputs without associated label element or aria-label.',
    check: 'structure',
  },
  {
    id: 'S05-MEDIUM-redundant-role',
    category: 'semantic',
    severity: 'MEDIUM',
    name: 'Redundant ARIA role',
    description: 'role attribute on element with implicit role (e.g., role="button" on <button>).',
    check: 'structure',
  },
  {
    id: 'S06-MEDIUM-missing-title',
    category: 'semantic',
    severity: 'MEDIUM',
    name: 'Missing page title',
    description: 'Page lacks <title> element or title is generic.',
    check: 'structure',
  },
  {
    id: 'V19-HIGH-low-contrast-muted',
    category: 'visual',
    severity: 'HIGH',
    name: 'Low contrast placeholder text',
    description: 'Placeholder text below 4.5:1 contrast. Placeholders are text too.',
    check: 'contrast',
  },
  {
    id: 'V20-MEDIUM-center-decorative',
    category: 'visual',
    severity: 'MEDIUM',
    name: 'Centered decorative layout',
    description: 'Content centered for aesthetic reasons without structural purpose.',
    check: 'layout',
  },
];

export const RULE_CATEGORIES = {
  accessibility: { code: 'A', name: 'Accessibility' },
  visual: { code: 'V', name: 'Visual Quality' },
  performance: { code: 'P', name: 'Performance' },
  interaction: { code: 'I', name: 'Interaction/UX' },
  semantic: { code: 'S', name: 'Semantic/SEO' },
};

export const SEVERITY_LEVELS = {
  CRITICAL: { priority: 1, action: 'Fix immediately', color: '\x1b[31m' },
  HIGH: { priority: 2, action: 'Fix before ship', color: '\x1b[33m' },
  MEDIUM: { priority: 3, action: 'Should fix', color: '\x1b[34m' },
  LOW: { priority: 4, action: 'Nice to have', color: '\x1b[36m' },
  INFO: { priority: 5, action: 'Consider', color: '\x1b[90m' },
};

export function getAntipattern(id) {
  return ANTIPATTERNS.find(rule => rule.id === id);
}

export function getRulesForCategory(category) {
  return ANTIPATTERNS.filter(rule => rule.category === category);
}

export function getRulesBySeverity(severity) {
  return ANTIPATTERNS.filter(rule => rule.severity === severity);
}

export function getRuleEngineSupport() {
  return {
    browser: true,
    staticHtml: true,
    regex: true,
    ml: true,
  };
}
